### ISSUE TITLE
测试集的设定

### ISSUE THREAD

**Issue by renqi1998** [SuperiorLeo/MFormer-Taming-Masked-Transformer-for-Unsupervised-Spectral-Reconstruction#1]
您好，我在运行您的代码时遇到问题，希望你能帮我解决一下。
“img_path = '/home/data/SSROriDataset/NTIRE2020/NTIRE2020_Validation_Clean/'
gt_path = '/home/data/SSROriDataset/NTIRE2020/NTIRE2020_Validation_Spectral/'”
请问测试集是从哪获取的？

**Comment by SuperiorLeo** [comment]
你好，这个是NTIRE2020 Spectral Reconstruction主办方官方划分的训练集和验证集，可以关注https://ieeexplore.ieee.org/document/9150756/
