### ISSUE TITLE
百度网盘链接失效

### ISSUE THREAD

**Issue by darkmingy** [SuperiorLeo/MFormer-Taming-Masked-Transformer-for-Unsupervised-Spectral-Reconstruction#2]
您好，请问可以重新分享一下NTIRE2020-CLEAN测试模型的链接吗

**Comment by darkmingy** [comment]
还有一个疑问，想问一下所提供的数据集是2022NTIRE的数据集吗？训练的时候用的是2020的数据集还是2022的数据集呢

**Comment by SuperiorLeo** [comment]
好的，我更新一下，训练的时候用的是2020的数据集哈。
